### ISSUE TITLE
 Closed GUI won't start if there's any buffer history in the default session

### ISSUE THREAD

**Issue by duikboot** [atlas-engineer/nyxt#1124]
I did a clean build today, and I encounter the same problem as this issue:
https://github.com/atlas-engineer/nyxt/issues/1070

─[$] <git:(master*)> ./nyxt -v
Arguments parsed: (VERBOSE T URLS NIL) and NIL
 <INFO> [21:28:00] nyxt start.lisp (listen-or-query-socket) -
  Listening to socket "/home/arjen/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-5-384-gbd649c62
 <INFO> [21:28:00] nyxt start.lisp (load-lisp unsafe-load) -
  Loading Lisp file "/home/arjen/.config/nyxt/auto-config.lisp".
<DEBUG> [21:28:00] nyxt renderer-gtk.lisp (ffi-initialize gtk-browser) -
  Initializing GTK Interface
<DEBUG> [21:28:00] nyxt base-mode.lisp (base-mode form-fun-26) -
  BASE-MODE enabled.
<DEBUG> [21:28:00] nyxt/web-mode web-mode.lisp (web-mode form-fun-30) -
  WEB-MODE enabled.
<DEBUG> [21:28:00] nyxt/vi-mode vi-mode.lisp (vi-normal-mode form-fun-42) -
  VI-NORMAL-MODE enabled.
 <INFO> [21:28:00] nyxt message.lisp (echo form-fun-6) -
  Loading history of 0 URLs from "/home/arjen/.local/share/nyxt/history/default.lisp".

_Originally posted by @duikboot in https://github.com/atlas-engineer/nyxt/issues/1070#issuecomment-772800709_

**Comment by Ambrevar** [comment]
Thanks for reporting.

I've just pushed a fix, can you try on
e87a42038ac70da23224cf68bc108754ef5f0a85 ?

**Comment by aartaka** [comment]
I can reproduce it. 7a2763d123d48939204320d6e3a51f8b689d4fb2 is the offending commit. e87a420 does not fix this, at least for me.

**Comment by duikboot** [comment]
Thanks for your quick reply, as @aartaka reports, it doesn't fix it. Sorry.

**Comment by Ambrevar** [comment]
I can't reproduce.

Can you share your ~/.local/share/nyxt/history/default.lisp if if does
not contain anything private?

If it does, maybe you could delete the history and reproduce the issue with
non-private URLs, then post the resulting file.

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> I can reproduce it. 7a2763d123d48939204320d6e3a51f8b689d4fb2 is the offending commit.

Indeed, this commit changes many things, in particular with regard to
startup.  We could revert it, but then we need to fix the owner
instantiation of buffers that are not created with make-buffer.

**Comment by aartaka** [comment]
Or we can analyse what goes wrong and fix it. I can try debugging it tonight.

**Comment by duikboot** [comment]
Here is the ~/.local/share/nyxt/history/default.lisp file
```
(:SEQUENCE 1 :CLASS LIST :SIZE 2 :ELEMENTS
 ("2-pre-release-5-388-ge87a4203"
  (:OBJECT 2 :CLASS HISTORY-TREE:HISTORY-TREE :SLOTS
   ((HISTORY-TREE:OWNERS :HASH-TABLE 3 :TEST EQUALP :SIZE 7 :REHASH-SIZE 1.5
                         :REHASH-THRESHOLD 1.0 :ENTRIES
                         (("1" :OBJECT 4 :CLASS HISTORY-TREE:OWNER :SLOTS
                           ((HISTORY-TREE:ORIGIN) (HISTORY-TREE:CREATOR-ID)
                            (HISTORY-TREE::CREATOR-NODE) (HISTORY-TREE:CURRENT)
                            (HISTORY-TREE:NODES)))
                          ("2" :OBJECT 5 :CLASS HISTORY-TREE:OWNER :SLOTS
                           ((HISTORY-TREE:ORIGIN :OBJECT 6 :CLASS
                                                 HISTORY-TREE:NODE :SLOTS
                                                 ((HISTORY-TREE:PARENT)
                                                  (HISTORY-TREE:CHILDREN)
                                                  (HISTORY-TREE:BINDINGS
                                                   :HASH-TABLE 7 :TEST EQL
                                                   :SIZE 7 :REHASH-SIZE 1.5
                                                   :REHASH-THRESHOLD 1.0
                                                   :ENTRIES
                                                   (((:REF . 5) :OBJECT 8
                                                     :CLASS
                                                     HISTORY-TREE::BINDING
                                                     :SLOTS
                                                     ((HISTORY-TREE::FORWARD-CHILD)
                                                      (HISTORY-TREE:LAST-ACCESS
                                                       . "2021-02-04T11:24:18.685455Z")))))
                                                  (HISTORY-TREE:ENTRY :OBJECT 9
                                                                      :CLASS
                                                                      HISTORY-TREE:ENTRY
                                                                      :SLOTS
                                                                      ((HISTORY-TREE::HISTORY
                                                                        :REF
                                                                        . 2)
                                                                       (HISTORY-TREE:DATA
                                                                        :OBJECT
                                                                        10
                                                                        :CLASS
                                                                        HISTORY-ENTRY
                                                                        :SLOTS
                                                                        ((URL
                                                                          . "https://nos.nl/")
                                                                         (TITLE
                                                                          . "NOS.nl - Nieuws, Sport en Evenementen | Nederlandse Omroep Stichting")
                                                                         (LAST-ACCESS
                                                                          . "")
                                                                         (EXPLICIT-VISITS
                                                                          . 0)
                                                                         (IMPLICIT-VISITS
                                                                          . 1)))
                                                                       (HISTORY-TREE:LAST-ACCESS
                                                                        . "2021-02-04T11:24:18.668744Z")
                                                                       (HISTORY-TREE:NODES
                                                                        :SEQUENCE
                                                                        11
                                                                        :CLASS
                                                                        LIST
                                                                        :SIZE 1
                                                                        :ELEMENTS
                                                                        ((:REF
                                                                          . 6)))))))
                            (HISTORY-TREE:CREATOR-ID)
                            (HISTORY-TREE::CREATOR-NODE)
                            (HISTORY-TREE:CURRENT :REF . 6)
                            (HISTORY-TREE:NODES :SEQUENCE 12 :CLASS LIST :SIZE
                                                1 :ELEMENTS ((:REF . 6)))))))
    (HISTORY-TREE:CURRENT-OWNER-ID . "2")
    (HISTORY-TREE:ENTRIES :HASH-TABLE 13 :TEST HISTORY-TREE::ENTRY-EQUAL-P
                          :SIZE 7 :REHASH-SIZE 1.5 :REHASH-THRESHOLD 1.0
                          :ENTRIES (((:REF . 9) :REF . 9)))
    (HISTORY-TREE:KEY . HISTORY-TREE-KEY) (HISTORY-TREE:TEST . EQUALP)
    (HISTORY-TREE:HASH-FUNCTION . SXHASH)))))
```

**Comment by Ambrevar** [comment]
Thanks for the file, Arjen.
It works on my machine though.  My guess is that this is a race
condition during startup.

Can you describe the symptoms as precisely as possible?  Does Nyxt show
a window?  Is it blank?  Can you use the minibuffer? Does it hang?  Does
it crash?  Does the shell process return?

What's remarkable from your shell output is this:

>	Loading history of 0 URLs from "/home/arjen/.local/share/nyxt/history/default.lisp".

While clearly there is 1 URL in this history file.  On my machine it
says

> <INFO> [15:59:12] Loading history of 1 URLs from "/home/ambrevar/.local/share/nyxt/history/default.lisp".

This means that deserialization failed.
Arjen, how did you install this version?
If you built from source, are you using Quicklisp?
If so, can you make sure it's up-to-date, in particular cl-prevalence
should be at the latest version or else it won't work.

All that said, even if Nyxt fails to restore the history, it should keep
going because we catch errors:

    (if *keep-alive*
        (%restore)
        (handler-case (%restore)
          (error (c)
            (echo-warning "Failed to restore history from ~a: ~a"
                          (expand-path path) c))))))

so my guess is that there is a race condition after that.
Could be https://github.com/atlas-engineer/nyxt/pull/1072 again.

**Comment by Ambrevar** [comment]
I can reproduce with (session-restore-prompt *browser*) set to
:always-ask (the default).

**Comment by duikboot** [comment]
Thanks again for looking at the bug.
I just updated quicklisp and cloned a fresh repo of nyxt, and used `make all` to build Nyxt.

It hangs at loading the history without showing anything, but it now shows that there is an url in the history file.

```
 └─[$] <git:(master*)> ./nyxt -v   
Arguments parsed: (VERBOSE T URLS NIL) and NIL
 <INFO> [16:34:50] nyxt start.lisp (listen-or-query-socket) -
  Listening to socket "/home/arjen/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-5-388-ge87a4203
 <INFO> [16:34:50] nyxt start.lisp (load-lisp unsafe-load) -
  Loading Lisp file "/home/arjen/.config/nyxt/auto-config.lisp".
<DEBUG> [16:34:50] nyxt renderer-gtk.lisp (ffi-initialize gtk-browser) -
  Initializing GTK Interface
<DEBUG> [16:34:50] nyxt base-mode.lisp (base-mode form-fun-26) -
  BASE-MODE enabled.
<DEBUG> [16:34:50] nyxt/web-mode web-mode.lisp (web-mode form-fun-30) -
  WEB-MODE enabled.
<DEBUG> [16:34:50] nyxt/vi-mode vi-mode.lisp (vi-normal-mode form-fun-42) -
  VI-NORMAL-MODE enabled.
 <INFO> [16:34:50] nyxt message.lisp (echo form-fun-6) -
  Loading history of 1 URLs from "/home/arjen/.local/share/nyxt/history/default.lisp".
```

**Comment by Ambrevar** [comment]
I've got a fix, @aartaka don't bother working on it, I'll push it a
little while.

**Comment by aartaka** [comment]
Sure!

**Comment by aartaka** [comment]
I was just inspecting and setting breakpoints around. Thanks for relieving me from this :)

**Comment by Ambrevar** [comment]
Arjen Dijkstra <notifications@github.com> writes:

> It hangs at loading the history without showing anything, but it now shows that there is an url in the history file.

So you had 2 bugs!  One is solved (by updated cl-prevalence), the other
fix is coming just now.

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> I was just inspecting and setting breakpoints around. Thanks for relieving me from this :)

I only needed stickers for this one ;)

**Comment by aartaka** [comment]
> I only needed stickers for this one ;)

I meant stickers by breakpoints :)

**Comment by duikboot** [comment]
Yes, I can confirm this solves the bug. Thanks a lot!
