### ISSUE TITLE
Startup errors sometimes yield a blank, mode-less buffer

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1172]
If I add an error to my init file and start Nyxt, it sometimes result in 2 windows:

- one with the error (as expected), 
- and another one which displays only a  blank canvas with no mode (!) instead of the `*Help*` page.  

This last window may seem particularly broken, especially to newcomes, use since only `C-space` works there.

**Comment by aartaka** [comment]
Is it fixed on `master`/`3-pre-release-1` with the proper error recovery?

**Comment by aartaka** [comment]
Closing, as it should be fixed.

**Comment by Ambrevar** [comment]
Yes.  We still have the problem of using dummy buffers which should not make the window unusable, but that's another problem.
