### ISSUE TITLE
History named storage/restoration does not work

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1865]
**Describe the bug**

`store-history-by-name` and `restore-history-by-name` don't work anymore. `store-history-by-name` stores this to the named file:
``` 
(:SEQUENCE 1 :CLASS LIST :SIZE 2 :ELEMENTS ("2.2.2" NIL))
```
While `restore-history-by-name` either does nothing to the history or (if you have not buffers open) opens `about:blank`.

**Precise recipe to reproduce the issue**
- Start Nyxt.
- Open some websites.
- Execute `store-history-by-name` and type any name you like.
- Open the file history got stored in. You'll see the output like above.
- Reopen Nyxt and _don't_ restore buffers.
- Execute `restore-history-by-name` and choose the default history file.
- It will open an `about:blank`.

**Information**
- OS name+version: Guix System Distribution `guix describe`:
```
Generation 49   Nov 08 2021 14:36:15    (current)
  guix f52719d
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: f52719dfad7b7d3beb2b1211b6846196f3590823
  chur 8fcb5dd
    repository URL: https://github.com/aartaka/chur-guix
    branch: master
    commit: 8fcb5ddaa15fd10d71c1e50950405bb6d48e4393
  nonguix f3a7d45
    repository URL: https://gitlab.com/nonguix/nonguix
    branch: master
    commit: f3a7d45740cbb7c91a5369c3992a4e8288cbc563
```
- Graphics card and driver: Intel UHD, `lspci -v`:
```
00:02.0 VGA compatible controller: Intel Corporation 8th Gen Core Processor Gaussian Mixture Model (prog-if 00 [VGA controller])
        DeviceName: Onboard - Video
        Subsystem: Lenovo Device 312d
        Flags: bus master, fast devsel, latency 0, IRQ 131
        Memory at b0000000 (64-bit, non-prefetchable) [size=16M]
        Memory at a0000000 (64-bit, prefetchable) [size=256M]
        I/O ports at 3000 [size=64]
        Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Root Complex Integrated Endpoint, MSI 00
        Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [d0] Power Management version 2
        Capabilities: [100] Process Address Space ID (PASID)
        Capabilities: [200] Address Translation Service (ATS)
        Capabilities: [300] Page Request Interface (PRI)
        Kernel driver in use: i915
```
- Desktop environment / Window manager name+version: StumpWM 20.11, `version` command reports `1.0.1 Compiled On Tue Sep 28 2021 12:11:52`
- How you installed Nyxt (Guix pack, package manager, build from source): `guix package -f nyxt.scm`
- Information from `show-system-information`:
```
Nyxt version: 2.2.2
Renderer version: GI-GTK
Operating system kernel: Linux 5.14.16
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 3221225472)
Features: (:SLYNK :QUICKLISP :WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-2
 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :GLOBAL-VARS
 :DECLARE-TYPES :PARENSCRIPT :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES
 :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-PPCRE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED
 :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CHIPZ-SYSTEM:GRAY-STREAMS CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64
 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP
 :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/r1h8xkrc3nj5rm0y1zkf91c971wbc6pa-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/v7scxd0n3rvwi3qxrmbig85nhfx97b0m-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/source/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/bya608vabw1kl0511y9yw71j93isx0p5-cl-webkit-3.1.0/share/common-lisp/source/cl-webkit/webkit2/cl-webkit2.asd)
```

**Output when started from a shell**
```
<INFO> [16:39:56] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.2.2
<INFO> [16:39:56] Loading Lisp file "/home/aartaka/.config/nyxt/init.lisp".
WARNING:
   redefining SB-GRAY:STREAM-LINE-LENGTH (#<STANDARD-CLASS SB-GRAY:FUNDAMENTAL-CHARACTER-INPUT-STREAM>) in DEFMETHOD
WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
WARNING: Key was bound to DELETE-CURRENT-BUFFER
WARNING: Key was bound to HISTORY-FORWARDS
SLYNK's ASDF loader finished.<INFO> [16:39:58] Not restoring session.
<INFO> [16:39:58] Loading history of 701 URLs from "/home/aartaka/.local/share/nyxt/history/default.lisp".
<INFO> [16:40:00] Loading 66 bookmarks from "/home/aartaka/.local/share/nyxt/bookmarks.lisp".
WARNING: Key was bound to DELETE-CURRENT-BUFFER
WARNING: Key was bound to HISTORY-FORWARDS
WARNING: Key was bound to RELOAD-WITH-MODES
<INFO> [16:40:03] Loading 10 auto-mode rules from "/home/aartaka/.local/share/nyxt/auto-mode-rules.lisp".
<INFO> [16:40:04] Loading "https://github.com/".
<INFO> [16:40:05] Finished loading "https://github.com/".
WARNING: Key was bound to DELETE-CURRENT-BUFFER
WARNING: Key was bound to HISTORY-FORWARDS
WARNING: Key was bound to RELOAD-WITH-MODES
<INFO> [16:40:11] Loading "https://github.com/atlas-engineer/nyxt/issues".
<INFO> [16:40:13] Finished loading "https://github.com/atlas-engineer/nyxt/issues".
<INFO> [16:40:20] History stored to "/home/aartaka/.local/share/nyxt/history//nyxt.lisp".
<INFO> [16:40:42] Deleting socket "/run/user/1000/nyxt/nyxt.socket".
```

**Comment by Ambrevar** [comment]
Should be fixed with 4f1b50544b9bd1375eadf127d8b2f26a15f2a88f.  @aartaka Can you confirm?

**Comment by aartaka** [comment]
No, it doesn't fix it fully. It doesn't store the history to a new named file somewhy. Restoration does work, but I only tested it with the default file.

**Comment by Ambrevar** [comment]
For me it only stores it _sometimes_.  I don't quite know why, maybe a
bug in the asynchronicity.
