### ISSUE TITLE
Incorrect usage of `LDFLAGS` in web-extensions Makefile

### ISSUE THREAD

**Issue by MithicSpirit** [atlas-engineer/nyxt#1967]
**Describe the bug**

The `LDFLAGS` variable is meant to be used with the compiler, not the linker:
> 'LDFLAGS'
>> Extra flags to give to compilers when they are supposed to invoke the linker, 'ld', such as '-L'.  Libraries ('-lfoo') should be added to the 'LDLIBS' variable instead.

-`info make`

However, in https://github.com/atlas-engineer/nyxt/blob/66171cdf053eadc4f1d0c247339129a036d74b57/libraries/web-extensions/Makefile#L10 it is used directly with the linker, which causes build issues if it is set correctly. Specifically, `LDFLAGS` should be set to a comma-separated list of flags beginning with `-Wl,`, which, when passed to a compiler like `gcc`, will be converted to the actual flags for the linker. 

**Precise recipe to reproduce the issue**
1. Install `docker` and pull the `archlinux:base-devel` image
2. Create the following file as `repro` in the pwd
```bash
pacman -Syu --needed --noconfirm git sbcl cl-asdf webkit2gtk glib-networking gsettings-desktop-schemas enchant pkgconf sudo gobject-introspection-runtime
echo "ALL ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

useradd build
mkdir -p /home/build
chown build /home/build

su - build -c '
git clone https://aur.archlinux.org/libfixposix.git
cd libfixposix 
makepkg -si --noconfirm
cd ..

git clone https://github.com/atlas-engineer/nyxt.git
cd nyxt
LDFLAGS='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now' make all
'
```
3. Execute `sudo docker run -it --rm -v "$PWD:/repro" archlinux:base-devel bash /repro/repro`

**Information**
- OS name+version: Arch Linux (rolling)
- How you installed Nyxt (Guix pack, package manager, build from source): [AUR -git package](https://aur.archlinux.org/packages/nyxt-browser-git/) (though also occurs when building directly from source)
- Information from `show-system-information`: (from previously installed version)
```lisp
Nyxt version: 2.1.1-1153-gc699812f
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.11-xanmod1-1
Lisp implementation: SBCL 2.1.11 (Dynamic space size: 1073741824)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/build/nyxt-browser-git/src/nyxt-browser/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /build/nyxt-browser-git/src/nyxt-browser/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /build/nyxt-browser-git/src/nyxt-browser/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

**Comment by aartaka** [comment]
22609093fcc47c641f9aa458e3efbebeab8618f2 should fix it.

**Comment by MithicSpirit** [comment]
That partially fixed it, but now the `LDLIBS` variable still has a `-Wl,…` flag (specifically, `-Wl,--export-dynamic`) because `pkg-config` includes it. Seems like a better fix would be to call the compiler and somehow tell it to just link the file so that it takes care of all of the `-Wl,` flags.

Alternatively, it may also be possible to use some scripting to alter all arguments beginning in `-Wl,` to remove that prefix and replace all commas with spaces.

**Comment by aartaka** [comment]
Then 2cde1237ec491d0f849ac7bcc93a9c9ded1a9b6c should be the ultimate fix :)

**Comment by MithicSpirit** [comment]
Great! It's fixed now. And I think that this means that 22609093fcc47c641f9aa458e3efbebeab8618f2 can be reverted too.

**Comment by aartaka** [comment]
> Great! It's fixed now. And I think that this means that [2260909](https://github.com/atlas-engineer/nyxt/commit/22609093fcc47c641f9aa458e3efbebeab8618f2) can be reverted too.

Indeed. Done in ece2c39789abb1434aaf2fff8baf534fc6407c16.
