### ISSUE TITLE
Download-mode is broken

### ISSUE THREAD

**Issue by shamazmazum** [atlas-engineer/nyxt#2489]
**Describe the bug**
When you start a download you cannot cancel it in the `*Downloads*` buffer. Status bar is not updated too. I am on 02bced0.

Dump from the terminal:

~~~~
vasily@vonbraun:~ % nyxt
Nyxt version 3-pre-release-1-143-gb321ab4b9
<INFO> [20:01:07] Source location: #P"/home/vasily/.quicklisp/dists/ultralisp/software/atlas-engineer-nyxt-20220729122821/"
<INFO> [20:01:07] Listening to socket #P"/var/run/user/1001/nyxt/nyxt.socket".
<INFO> [20:01:07] Loading Lisp file #P"/home/vasily/.config/nyxt/config.lisp".
<INFO> [20:01:07] GTK extensions directory: #P"/home/vasily/.quicklisp/dists/ultralisp/software/atlas-engineer-nyxt-20220729122821/libraries/web-extensions/"
<INFO> [20:01:07] GTK extensions directory: #P"/home/vasily/.quicklisp/dists/ultralisp/software/atlas-engineer-nyxt-20220729122821/libraries/web-extensions/"
<INFO> [20:01:07] Loading #P"/home/vasily/.local/share/nyxt/history/default.lisp".
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
<INFO> [17:01:10] Loading #P"/home/vasily/.local/share/nyxt/bookmarks.lisp".
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
<INFO> [17:01:12] Loading "https://duckduckgo.com/?q=debian".
<INFO> [17:01:14] Finished loading "https://duckduckgo.com/?q=debian&ia=web".
<INFO> [17:01:14] Loading "https://duckduckgo.com/?q=debian&ia=web".
<INFO> [17:01:16] Finished loading "https://www.debian.org/".
<INFO> [17:01:16] Loading "https://www.debian.org/".
<INFO> [17:01:17] Finished loading "https://www.debian.org/download".
<INFO> [17:01:18] Loading "https://www.debian.org/download".
<INFO> [17:01:19] Failed to load URL https://gemmei.ftp.acc.umu.se/debian-cd/current/amd64/iso-cd/debian-11.4.0-amd64-netinst.iso in buffer 629.
<INFO> [17:01:19] Destination "/home/vasily/Downloads/debian-11.4.0-amd64-netinst.iso" exists, saving as "/home/vasily/Downloads/debian-11.4.0-amd64-netinst.iso.1".
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
<INFO> [17:01:19] Finished loading "https://www.debian.org/download".
<WARN> [17:01:19] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:3:19: TypeError: null is not an object (evaluating 'element.textContent = 'Bytes downloaded: 111900'')
<WARN> [17:01:19] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:3:19: TypeError: null is not an object (evaluating 'element.style')
<WARN> [17:01:19] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: undefined:3:19: TypeError: null is not an object (evaluating 'element.textContent = 'Completion: 0.03%'')
<WARN> [17:01:26] Request lisp://1627/cancel-download is bound to no callback for buffer #<WEB-BUFFER 1629 {10196684E3}>
<WARN> [17:01:26] Request lisp://1627/cancel-download is bound to no callback for buffer #<WEB-BUFFER 1629 {10196684E3}>
<WARN> [17:01:27] Request lisp://1627/cancel-download is bound to no callback for buffer #<WEB-BUFFER 1629 {10196684E3}>
<WARN> [17:01:27] Request lisp://1627/cancel-download is bound to no callback for buffer #<WEB-BUFFER 1629 {10196684E3}>
<WARN> [17:01:27] Request lisp://1627/cancel-download is bound to no callback for buffer #<WEB-BUFFER 1629 {10196684E3}>
<WARN> [17:01:27] Request lisp://1627/cancel-download is bound to no callback for buffer #<WEB-BUFFER 1629 {10196684E3}>
~~~~

It seems that `nyxt/ps:lisp-eval` in `source/mode/download.lisp` installs callbacks for the wrong buffer (the buffer from where download was started, not the one named `*Downloads*`).
Sorry, if it's a duplicate, this bug is hard to miss. Currently I do not have any ideas how to fix it ;) `nyxt/ps:lisp-eval` has a `buffer` argument, but `*Downloads*` is created after `nyxt/ps:lisp-eval` was called, as it seems.

**Comment by aartaka** [comment]
Woooooo, that's intriguing `\( ‘з’)/`

**Comment by Ambrevar** [comment]
Note: We _really_ need a download test!  But the download API is very hard to test...

**Comment by shamazmazum** [comment]
This fixes buttons because when `(setf (cancel-function ...) ...)` is called `*Downloads*` becomes current buffer and `nyxt/ps:lisp-eval` installs callbacks correctly. I am still working on the progress bar.

~~~~
diff --git a/source/renderer/gtk.lisp b/source/renderer/gtk.lisp
index df5cc4875..0392e8729 100644
--- a/source/renderer/gtk.lisp
+++ b/source/renderer/gtk.lisp
@@ -1768,6 +1768,7 @@ local anyways, and it's better to refresh it if a load was queried."
                                        :url (webkit:webkit-uri-request-uri
                                              (webkit:webkit-download-get-request webkit-download))
                                        :gtk-object webkit-download)))
+    (nyxt/download-mode:list-downloads)
     (setf (nyxt/download-mode::cancel-function download)
           #'(lambda ()
               (setf (nyxt/download-mode:status download) :canceled)
@@ -1800,10 +1801,7 @@ local anyways, and it's better to refresh it if a load was queried."
       (setf (nyxt/download-mode:destination-path download)
             (uiop:ensure-pathname
              (quri:uri-path (quri:uri
-                             (webkit:webkit-download-destination webkit-download)))))
-      ;; TODO: We should not have to update the buffer, button actions should be
-      ;; dynamic.  Bug in `user-interface'?
-      (nyxt/download-mode:list-downloads))
+                             (webkit:webkit-download-destination webkit-download))))))
     (connect-signal download "failed" nil (webkit-download error)
       (declare (ignore error))
       (unless (eq (nyxt/download-mode:status download) :canceled)
~~~~

**Comment by aartaka** [comment]
Thanks for narrowing it down to this! I've pushed the fix to master. 

While a better fix would be to somehow fix the `lisp-eval` reliance on buffers, this one fixes the problem too.

**Comment by shamazmazum** [comment]
NP, but the issue is not fixed yet. I can cancel a download, but, as I said, the progress bar is not working.
![20220803_10h42m23s_grim](https://user-images.githubusercontent.com/812069/182552769-641654da-f5ac-4ba7-aa59-f9c80206bf84.png)

Can you reopen please?

**Comment by aartaka** [comment]
Ouch :sweat_smile:

**Comment by shamazmazum** [comment]
The progress bar was easy to fix ;)
