### ISSUE TITLE
Add help-mode to describe-* pages and other help interfaces

### ISSUE THREAD

**Issue by franburstall** [atlas-engineer/nyxt#2540]
**Describe the bug**
Not sure if this is a bug or a feature request.

If I open the manual, I get a buffer with `help-mode` activated.  This has a useful keymap with single character bindings for things like `next-heading` and `kill-current-buffer`.   All of this is very lovely and helps an emacs-user feel at home.

However, other help buffers such as those built by `describe-command` do not have this mode activated.  Is this deliberate or an oversight?

**Information**
- OS name+version: debian-11
- Desktop environment / Window manager name+version: exwm
- How you installed Nyxt (Guix pack, package manager, build from source): source
- Information from `show-system-information`:
```
Nyxt version: 3-pre-release-1-349-g70ce3f37
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.0-17-amd64
Lisp implementation: SBCL 2.1.1 (Dynamic space size: 3221225472)
Features: (:QUICKLISP :NYXT-GI-GTK :NYXT-GTK :WEBKIT2 :WEBKIT2-2.36
 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-3.1 :NYXT-3 :CUSTOM-HASH-TABLE-NATIVE :SLYNK
 :PLUMP-UTF-32 :PARENSCRIPT :FSET-EXT-STRINGS :GLOBAL-VARS :DECLARE-TYPES
 :NAMED-READTABLES :SWANK :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-PPCRE :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS
 :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER
 :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64
 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP
 :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE
 CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3
 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC
 :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/fran/common-lisp/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/fran/common-lisp/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)


```

**Output when started from a shell**

**Comment by aartaka** [comment]
I mean, the bindings are less useful in `describe-*` pages which are smaller (usually aroung one or two screens in length) and have less content nesting.

But then, yes, it may still be useful to enable `help-mode` there.

The binding listing problem is #2534.

**Comment by franburstall** [comment]
It would be worth it just for the `q` keybind!

**Comment by franburstall** [comment]
I looked further at this (given the `good-first-issue` tag) and found that the intention to fire `help-mode` on `describe-*` pages is already present in the code.  At least, that is how I interpret the form
```
(buffer (str:concat "*Help-" (symbol-name variable) "*") (resolve-symbol :help-mode :mode))
```
present near the top of each `define-internal-page-command-global` in `describe.lisp`.  The last element here is supposed to set the `page-mode`, no?

So there really is a bug here: `help-mode` is *not* set in these pages.  

I did attempt to go further with this but got lost in a twisty maze of macro expansions....

**Comment by franburstall** [comment]
More on this: `(resolve-symbol :help-mode :mode)` does not reliably evaluate to the symbol `nyxt/help-mode:helpmode`.   In the sly repl, it often evaluates to `nil`.

In the definition of `describe-variable`, if I replace that form by the symbol, I get `help-mode` activated in `describe-variable` pages.

**Comment by aartaka** [comment]
Indeed, `resolve-symbol` does not find `help-mode`. `(nyxt:resolve-symbol :help-mode :mode (list :nyxt/help-mode))` does, because default list of packages in `resolve-symbol` does not include `nyxt/help-mode` somewhy.

**Comment by aartaka** [comment]
Using symbol is not an option, because compiler will be upset at `nyxt/help-mode:help-mode` symbol being used before it's defined.

**Comment by aadcg** [comment]
> Using symbol is not an option, because compiler will be upset at nyxt/help-mode:help-mode symbol being used before it's defined.

I vaguely remember facing this issue.

I agree that `help-mode` should be enabled in `decribe` buffers.

**Comment by franburstall** [comment]
> Using symbol is not an option, because compiler will be upset at `nyxt/help-mode:help-mode` symbol being used before it's defined.

Using the symbol is what `manual` does.

**Comment by aadcg** [comment]
That is correct, but I believe the compiler doesn't shout at us since that symbol is used on macros.

**Comment by Ambrevar** [comment]
No, it's because `manual.lisp` i loaded _after_ `mode/help.lisp`.

**Comment by aadcg** [comment]
Loading means when Nyxt starts?

**Comment by aartaka** [comment]
@aadcg, no, @Ambrevar meant `manual.lisp` is ASDF-loaded after `mode/help.lisp` and thus `nyxt/help-mode:help-mode` is already defined by the time `manual.lisp` is being compiled, and that's why there are no errors.

**Comment by aadcg** [comment]
Ok, all clear now. My mental map of `nyxt.asd`'s DAG was wrong.

The issue is that `describe.lisp` is loaded before `help-mode`.

**Comment by aadcg** [comment]
Perhaps the commands and internal pages from `describe.lisp` could be moved a to new file that would be loaded no sooner than the all of the Help module files.

**Comment by aartaka** [comment]
Or to mere `help.lisp` ¯\\\_(ツ)_/¯

**Comment by franburstall** [comment]
Another data point on `resolve-symbol`.  In a fresh nyxt session, I connect to emacs via sly and do:
```
NYXT-USER> (resolve-symbol :help-mode :mode)
NIL
T
NYXT-USER> (resolve-symbol :help-mode :mode '(:nyxt))
NYXT/HELP-MODE:HELP-MODE
NIL
```
Observe that the second value of the first call is `T` telling us that the first value is from the cache.

So it looks like `resolve-symbol` is somehow run during start up before the symbol `NYXT/HELP-MODE:HELP-MODE` is available and so caching the `nil` result.

**Comment by Ambrevar** [comment]
Looks like this is fixed with https://github.com/atlas-engineer/nyxt/commit/2d13e58ddeab879f49705698bf36f20465d8e0b1 and 8a1e81a8b5be624a494d1c953cff84c003894332.

OK to close?

**Comment by aartaka** [comment]
@Ambrevar, nope, `help-mode` is still not present in `describe-variable`, `describe-class`, and `describe-function` somewhy...

**Comment by franburstall** [comment]
No.  describe-* pages still don't have `help-mode` activated for me.  This is for Version 3-pre-release-1-437-gc2354c59

**Comment by Ambrevar** [comment]
The problem indeed is that describe.lisp is loaded before `mode/help.lisp`, and thus the symbol resolution expands to nil.

If you run it from the REPL and re-evaluate `describe.lisp` after startup, the pages will have the help-mode as expected.

So we need to fix the load order.  Moving describe.lisp after the core modes won't do, because `mode/prompt-buffer` depends on `resolve-backtick-quote-links`.

We need to split some files...

**Comment by Ambrevar** [comment]
See #2568.

**Comment by Ambrevar** [comment]
Feel free to reopen this if there is anything else.
