### ISSUE TITLE
Starting Nyxt from REPL in GNOME

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2734]
I start Nyxt from the sly REPL with:

- `(asdf:load-system "nyxt/gi-gtk")`
- `(nyxt:start)`

This has always worked for me on EXWM.

Recently, I've installed GNOME and decided to log into it. But I can't start Nyxt following the steps above. I'm extremely surprised to say the least. The desktop/window manager is different, but all the rest is the same. @Ambrevar can you make sense of this?

```log
Unhandled memory fault at #x18.
   [Condition of type SB-SYS:MEMORY-FAULT-ERROR]

Restarts:
 0: [ABORT-FFI-METHOD] Pass condition to calling thread.
 1: [ABORT] abort thread (#<THREAD "Nyxt renderer thread" RUNNING {1007AB9AF3}>)

Backtrace:
 0: (SB-SYS:MEMORY-FAULT-ERROR #<unused argument> #.(SB-SYS:INT-SAP #X00000018))
 1: ("foreign function: call_into_lisp_")
 2: ("foreign function: funcall2")
 3: ("foreign function: handle_memory_fault_emulation_trap")
 4: ("foreign function: #x41C20E")
 5: (GOBJECT::CALL-GOBJECT-CONSTRUCTOR "WebKitWebView" ("web-context") (#<NYXT/RENDERER/GTK::WEBKIT-WEB-CONTEXT-EPHEMERAL {1008BCD343}>) (NIL))
 6: (GOBJECT::CREATE-GOBJECT-FROM-CLASS #<GOBJECT:GOBJECT-CLASS NYXT/RENDERER/GTK::WEBKIT-WEB-VIEW-EPHEMERAL> (:WEB-CONTEXT #<NYXT/RENDERER/GTK::WEBKIT-WEB-CONTEXT-EPHEMERAL {1008BCD343}>))
 7: ((:METHOD MAKE-INSTANCE (GOBJECT:GOBJECT-CLASS)) #<GOBJECT:GOBJECT-CLASS NYXT/RENDERER/GTK::WEBKIT-WEB-VIEW-EPHEMERAL> :WEB-CONTEXT #<NYXT/RENDERER/GTK::WEBKIT-WEB-CONTEXT-EPHEMERAL {1008BCD343}>) [fa..
 8: ((:METHOD NYXT:FFI-BUFFER-MAKE (NYXT/RENDERER/GTK:GTK-BUFFER)) #<NYXT:STATUS-BUFFER 1032 {100886E423}>) [fast-method]
 9: ((:METHOD NYXT:CUSTOMIZE-INSTANCE :AFTER (NYXT/RENDERER/GTK:GTK-BUFFER)) #<NYXT:STATUS-BUFFER 1032 {100886E423}> :EXTRA-MODES NIL :NO-HOOK-P NIL) [fast-method]
10: ((SB-PCL::EMF NYXT:CUSTOMIZE-INSTANCE) #<unused argument> #<unused argument> #<NYXT:STATUS-BUFFER 1032 {100886E423}>)
11: ((:METHOD MAKE-INSTANCE :AROUND (NYXT:USER-CLASS)) #<NYXT:USER-CLASS NYXT:STATUS-BUFFER>) [fast-method]
12: ((:METHOD SHARED-INITIALIZE (SB-PCL::SLOT-OBJECT T)) #<NYXT:WINDOW 1031 {10086A63A3}> T) [fast-method]
13: ((SB-PCL::EMF INITIALIZE-INSTANCE) #<unused argument> #<unused argument> #<NYXT:WINDOW 1031 {10086A63A3}>)
14: ((:METHOD MAKE-INSTANCE (CLASS)) #<NYXT:USER-CLASS NYXT:WINDOW>) [fast-method]
15: ((:METHOD MAKE-INSTANCE :AROUND (NYXT:USER-CLASS)) #<NYXT:USER-CLASS NYXT:WINDOW>) [fast-method]
16: ((LAMBDA NIL :IN NYXT:FFI-WINDOW-MAKE))
17: ((LAMBDA (GDK::DATA) :IN "/gnu/store/645aw72xipbsa5kngaxqb8cxnhmif8h0-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gdk/gdk.threads.lisp") #.(SB-SYS:INT-SAP #X00000004))
18: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/gnu/store/645aw72xipbsa5kngaxqb8cxnhmif8h0-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/glib/glib.main-lo..
19: ("foreign function: funcall_alien_callback")
 --more--
```

**Comment by Ambrevar** [comment]
This is almost surely an issue on your side: your environment seems to be referring to the wrong WebKit library.

Make sure to rebuild your execution environment, that should fix it.

Can you share how you start Nyxt?

**Comment by aadcg** [comment]
I start Nyxt via `nyxt-make-guix-sbcl-for-nyxt`. Passing `:force t` doesn't solve it.

I also thought it must be coking from my side but here's the interesting part: I log into EXWM, and it works; log out; log into GNOME and it doesn't. I have done this over 10 times now and I can't believe it...

**Comment by Ambrevar** [comment]
Try without `nyxt-make-guix-sbcl-for-nyxt`.
This helper generates a Lisp image which may run out of date.

**Comment by Ambrevar** [comment]
Yes, it's all in `documents/README.org`.

**Comment by aadcg** [comment]
I'll investigate this later. Something fishy is going on here.

**Comment by Ambrevar** [comment]
My guess is that when you start EXWM, files like ~/.xinitrc are parsed, while when you start from GNOME they are not.
Also check ~/.profile and ~/.xprofile

**Comment by aadcg** [comment]
I don't have any of those files, so it can't come from there. 

The relevant profile that `nyxt-guix.el` loads is the one located at `~/.guix-temp-profiles/nyxt/nyxt/etc/profile`. That profile behaves the same, regardless of the WM/DE. 

Still thinking on why this might be happening.

**Comment by Ambrevar** [comment]
Sorry for the delay, this fell under my radar.

So I tried on GNOME and could reproduce.  I'm not sure what is causing this, but it's clear it's coming from a bug in `nyxt-guix.el`.

There is an easy workdaround: Regenerate the image with `(nyxt-make-guix-sbcl-for-nyxt ... :force t)`, then you should be good to go.  After regenerating the image, I can switch Desktop Environment and it works as expected.

**Comment by aadcg** [comment]
Thanks for looking into it.

It remains a mystery to me why it's needed to force the image regeneration.
