### ISSUE TITLE
WebKit specific folders created at repository subtree

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2787]
I've noticed recently that WebKit folders are being created at my Nyxt's repository subtree. That's the first time I observe this behavior. For instance:

```log
source/CacheStorage/
source/WebKitCache/
source/localstorage/
source/mode/CacheStorage/
source/mode/WebKitCache/
```

Has anyone seen it? @aartaka @Ambrevar

**Comment by Ambrevar** [comment]
This used to happen with `--failsafe` for a while.
https://github.com/atlas-engineer/nyxt/commit/6e567fc63110081e47ee4b76879a7a1951203420 should fix it.
Can you reproduce on master?

**Comment by aadcg** [comment]
Thanks @Ambrevar, it seems that it fixed it!

**Comment by aadcg** [comment]
@Ambrevar I'm afraid I'm still having this issue when using `--failsafe`. Can you reproduce on your end? Thanks.

**Comment by Ambrevar** [comment]
Yes, I can reproduce.  Hmm...  @aartaka any idea?

**Comment by aartaka** [comment]
I can reproduce, and with some interesting properties of it:
- The directories are created in the directory Nyxt runs in.
- Most of the WebKitDataManager directories end up empty and, supposedly, resolved into the current directory.
- `nofile-profile` seems to not propagage into WebKitDataManager (there's `files:resolve` for `nosave-profile`, but not the `nofile-profile`), which seems to be the root of ~all evil~ this issue.

@Ambrevar, do you have a clear picture for how to resolve those? In case you're busy or want someone to finally learn `nfiles` well enough to fix such things, I am ready to address this someday and learn some `nfiles` :)

**Comment by aartaka** [comment]
So 8cee9d6444feabfd8c527c58a5ed2419ae1c1adc should fix it. @Ambrevar, @aadcg, can you test one more time to make sure I didn't hallucinate the fix working :)

**Comment by Ambrevar** [comment]
Nice, and good catch!

Then I guess 6e567fc63110081e47ee4b76879a7a1951203420 can be reverted (if the `and-let*` condition is changed to check for `nfiles/pathname:nil-pathname-p`.

**Comment by aadcg** [comment]
It seems to have fixed it for me, thanks!

**Comment by aartaka** [comment]
> Then I guess [6e567fc](https://github.com/atlas-engineer/nyxt/commit/6e567fc63110081e47ee4b76879a7a1951203420) can be reverted (if the `and-let*` condition is changed to check for `nfiles/pathname:nil-pathname-p`.

Reverted in 241d5db42128cebf3a418678a20b36d6ba1fe1d5. Closing this.

**Comment by Ambrevar** [comment]
Thanks!
