### ISSUE TITLE
list-bookmarks failure to load

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2899]
**Describe the bug**
list-bookmarks returns a 

> Page could not be loaded.
> URL: nyxt:nyxt/bookmark-mode:list-bookmarks
> Try again in a moment, maybe the site will be available again.
> If the problem persists for every site, check your Internet connection.
> Make sure the URL is valid.

**Precise recipe to reproduce the issue**
CUA bindings mode, I have bookmarks saved (I can access them with history-panel without issue)
For website-specific issues:

**Information**
- OS name+version:
``` sh
Ubuntu 22.04.2 LTS
```
- Graphics card and driver:
``` sh
Mesa Intel® HD Graphics 520 (SKL GT2)
```
- Desktop environment / Window manager name+version:
`wayland`
- How you installed Nyxt (Guix pack, package manager, build from source):
`unpacked the .tar`
- Information from `show-system-information`:
```
Nyxt version: 3
Renderer: GI-GTK
Operating system kernel: Linux 5.19.0-38-generic
Lisp implementation: SBCL 2.3.2 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-3 :CLIPBOARD-CONTENT-METHOD :SLYNK :PLUMP-UTF-32
 :PARENSCRIPT :NSYMBOLS :FSET-EXT-STRINGS :SBCL+SAFE-STANDARD-READTABLE
 :NAMED-READTABLES :NJSON :GLOBAL-VARS :SWANK :CL-FAD :LPARALLEL :21BIT-CHARS
 :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE
 :CHUNGA :FLEXI-STREAMS :WEBKIT2 :WEBKIT2-2.38 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :ASDF-SYSTEM-CONNECTIONS :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE
 CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3
 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR
 :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX
 :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB
 :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/qa0rc56xjnvgxy0ydskdzy86jjxs9hlz-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/qh9fn1h8mgyvij3j1iyi6a88dfqqazii-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/source/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/v9d47i6vwjxy2jsby8snxs76sxfcqiw2-cl-webkit-3.5.7/share/common-lisp/source/cl-webkit/webkit2/cl-webkit2.asd)


```

**Comment by jmercouris** [comment]
I believe this is fixed on master :-)

**Comment by tekakutli** [comment]
im on master, it still doesn't work https://files.catbox.moe/ujl1my.png

**Comment by jmercouris** [comment]
My apologies, you are absolutely right! I was thinking of `show-annotations` which I just fixed!
